### ISSUE TITLE
Game crashes when it tries to give me Tinted Rock

### ISSUE THREAD

**Issue by EnGerzard** [lobbienjonsji/StuffTheSpire#4]
Selected relic: null. Regenerating if canSpawn is false.
Selected mod: StuffTheSpire
Selected relic: StuffTheSpire:TintedRock. Regenerating if canSpawn is false.
Exception: java.lang.IllegalArgumentException: n must be positive
22:10:23.117 ERROR core.CardCrawlGame> Exception caught
java.lang.IllegalArgumentException: n must be positive
	at com.badlogic.gdx.math.RandomXS128.nextLong(RandomXS128.java:110) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.math.RandomXS128.nextInt(RandomXS128.java:99) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.random.Random.random(Random.java:65) ~[desktop-1.0.jar:?]
	at relicBalancer.patches.GetRelicPatch.Prefix(GetRelicPatch.java:39) ~[relicBalancer.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.returnRandomRelicKey(AbstractDungeon.java) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.returnRandomNonCampfireRelic(AbstractDungeon.java:906) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.addNoncampRelicToRewards(AbstractRoom.java:729) ~[?:?]
	at com.megacrit.cardcrawl.rooms.MonsterRoomElite.dropReward(MonsterRoomElite.java:100) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:425) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2494) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:871) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:422) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:

**Comment by lobbien** [comment]
Yup, it's an error with relic equalizer
