### ISSUE TITLE
Bug Crash - FrostArchetype relic created a NullPointerException

### ISSUE THREAD

**Issue by Clauvin** [lobbienjonsji/StuffTheSpire#5]
**What happenned:** While playing a heavily modded StS run, FrostArchetype effect resulted in a NullPointerException that crashed the game.

**How it happened:** First, I got a relic which completely randomized all future relics that spawned in the run. This meaning that FrostArchetype appeared as a reward after a combat, even being an Event Relic.

Then, after defeating a Mimic...

`03:00:55.265 INFO infinitespire.InfiniteSpire> InfiniteSpire | Saving Data...
03:00:55.267 INFO HubrisMod> Saving Data
03:00:55.270 DEBUG helpers.AsyncSaver> Enqueue: qsize=0 file=saves\TheAdministrix.autosave
03:00:55.270 DEBUG helpers.FileSaver> Dequeue: qsize=0 file=saves\TheAdministrix.autosave
03:00:55.270 DEBUG helpers.File> Attempting to save file=C:\Program Files (x86)\Jogos\Steam\steamapps\common\SlayTheSpire\saves\TheAdministrix.autosave
03:00:55.284 INFO cards.CardGroup> ERROR: No cards left for type: UNSPECIFIED
03:00:55.298 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at StuffTheSpire.relics.FrostArchetype.onTrigger(FrostArchetype.java:40) ~[StuffTheSpire.jar:?]
	at StuffTheSpire.patches.relics.AbstractRoomUpdatePatch.Insert(AbstractRoomUpdatePatch.java:48) ~[StuffTheSpire.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:453) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:28) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2494) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:871) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:422) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
03:00:55.300 DEBUG helpers.File> Successfully saved file=C:\Program Files (x86)\Jogos\Steam\steamapps\common\SlayTheSpire\saves\TheAdministrix.autosave
`

Leaving full log attached with this issue below.

[SlayTheSpire.log](https://github.com/lobbienjonsji/StuffTheSpire/files/3692830/SlayTheSpire.log)

**Comment by lobbien** [comment]
All Archetype relics are remove for now, until archetype api gets an update.
